// File generated by Zencoder based on android/app/google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsyyTGb7z-MkG5XkNP42DL_a3cnkQGmz8',
    appId: '1:388587154944:android:f7a3f5d6e204499813f2e5',
    messagingSenderId: '388587154944',
    projectId: 'dvsfsdfsdfds',
    storageBucket: 'dvsfsdfsdfds.firebasestorage.app',
  );
}
