// File generated by Zencoder based on android/app/google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNmri78Eo5mF-vtg8zV6T4dlQkjn5F98',
    appId: '1:660088162203:android:83426a5d233315a2f4433e',
    messagingSenderId: '660088162203',
    projectId: 'dbflutter-263b0',
    storageBucket: 'dbflutter-263b0.firebasestorage.app',
  );
}
